[IV-23-24] Objetivo 3: Automatización de operaciones
marinajcs/asignacionTareas pull request #21
Opened 2023-11-14 18:47 UTC by marinajcs

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-11-14 19:54 UTC, PabloBarTo approved these changes
Yo lo veo en general todo bien. Aunque por poner alguna pega, a la hora de elegir cualquier gestor pondría unos criterios antes de las explicaciones de los gestores y basaría estas explicaciones en función de esos criterios.

2023-11-15 18:56 UTC, marinajcs commented
> Yo lo veo en general todo bien. Aunque por poner alguna pega, a la hora de elegir cualquier gestor definiría unos criterios antes de las explicaciones de los gestores y basaría las explicaciones de estos en esos criterios.

Entendido, gracias por la sugerencia

2023-11-15 19:06 UTC, marinajcs commented
Listo para revisión @JJ

2023-11-15 19:25 UTC, JJ requested changes
Antes de revisar con más extensión el resto, mira que en la lista de comprobación pone explícitamente que se debe comprobar sólo la sintaxis. Se trata de que no necesitéis instalar ninguna herramienta externa, precisamente.

2023-11-15 19:25 UTC, JJ commented on Gruntfile.js
> +        eslint: {
eslint es un comprobador de buenas prácticas, no de sintaxis.

2023-11-16 09:56 UTC, marinajcs commented on Gruntfile.js
> +        eslint: {
Corregido en https://github.com/marinajcs/asignacionTareas/pull/21/commits/5bd71d42f4224c1aad2dae6a474a512ac6ec30ff

2023-11-16 10:39 UTC, JJ requested changes
Realmente no hay ninguna de las objeciones que sea crítica; si acaso el no haber desinstalado eslint de la forma correcta, pero en conjunto sí es cierto que podría mejorar un poco para superar el objetivo. Está muy cerca, en todo caso, y gracias a @PabloBarTo por la ayuda prestada.

2023-11-16 10:39 UTC, JJ commented on docs/gestor-tareas.md
> +* *Descripción*: Gulp es un sistema de construcción y automatización de tareas para JavaScript. Se utiliza para realizar tareas repetitivas como la minificación de archivos, la compilación de preproc
Gulp está irremediablemente obsoleto, me temo.

2023-11-16 10:39 UTC, JJ commented on docs/gestor-tareas.md
> +Para el desarrollo de una solución para el problema de la asignación de tareas en un piso de estudiantes, tanto Gulp como Grunt pueden ser adecuados; sin embargo, podría tener sentido
Podías haber incluido aquí también npm run, pnpm run y yarn run, que los vas a tener disponibles siempre.

2023-11-16 10:39 UTC, JJ commented on docs/runtime.md
> +### Navegador
Esto no hace falta que lo pongas. No vas a ejecutar un servidor web en el navegador.

2023-11-16 10:39 UTC, JJ commented on package.json
> +    "eslint": "^8.53.0",
No has quitado las dependencias que no vas a usar. Deberías desinstalarlas de la forma correcta.

2023-11-16 12:24 UTC, marinajcs commented on package.json
> +    "eslint": "^8.53.0",
Corregido en https://github.com/marinajcs/asignacionTareas/pull/21/commits/9340bc8648701019d25510853b614bcbd63e7cbf

2023-11-16 12:25 UTC, marinajcs commented on docs/runtime.md
> +### Navegador
Corregido en https://github.com/marinajcs/asignacionTareas/pull/21/commits/dd57e1dd7ad5311684205aa9370680d4614d50e7

2023-11-16 12:25 UTC, marinajcs commented on docs/gestor-tareas.md
> +Para el desarrollo de una solución para el problema de la asignación de tareas en un piso de estudiantes, tanto Gulp como Grunt pueden ser adecuados; sin embargo, podría tener sentido
Corregido en https://github.com/marinajcs/asignacionTareas/pull/21/commits/06fb0dc880ac99d3d56d8be3c6c7c92e8d5258c1

2023-11-16 12:25 UTC, marinajcs commented on docs/gestor-tareas.md
> +* *Descripción*: Gulp es un sistema de construcción y automatización de tareas para JavaScript. Se utiliza para realizar tareas repetitivas como la minificación de archivos, la compilación de preproc
Corregido en https://github.com/marinajcs/asignacionTareas/pull/21/commits/06fb0dc880ac99d3d56d8be3c6c7c92e8d5258c1

2023-11-16 12:35 UTC, JJ requested changes
Me temo que deno no es un gestor de dependencias, salvo que elijas deno como runtime y efectivamente uses sus ficheros para gestionar dependencias. Por favor, repasa qué son deno, bun y node y ajusta las elecciones y documentación en consonancia.

2023-11-16 12:35 UTC, JJ commented on docs/gestor-dependencias.md
> +### deno
Deno sólo es una opción si lo eliges como runtime. Bun sí es una opción, porque es compatible con node. Por favor, trata de repasar qué hace cada uno.

2023-11-16 13:18 UTC, marinajcs commented on docs/gestor-dependencias.md
> +### deno
Corregido en https://github.com/marinajcs/asignacionTareas/pull/21/commits/d7f9ee6f38ce81cacfdc4ead2df6c1150cd5f5a6

Entendido, no tenía sentido incluir Deno entre las opciones de gestor de dependencias si no se ha elegido como runtime. También he incluido Bun como opción tanto en runtime como en gestor de dependencias, ya que sí es
compatible con node.

2023-11-16 13:21 UTC, JJ approved these changes
:+1:

2023-11-17 08:14 UTC, merged