ÌV-23-24] Objetivo 5: Creación de un contenedor para pruebas
marinajcs/asignacionTareas pull request #33
Opened 2023-12-11 19:50 UTC by marinajcs

* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [ ] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

2023-12-16 17:08 UTC, migueruiz approved these changes
Hola, seré tu revisor! Veo todo tu documento correctamente, por ponerle alguna pega, lo que te he dejado abajo. Pero en principio, lo veo todo correctamente! 😄

2023-12-16 17:08 UTC, migueruiz commented on Dockerfile
> +LABEL maintainer="marinacarranza@correo.ugr.es"
Deberías de indicar también la versión. Puedes mirar en mi repositorio si lo necesitas. 😆

2023-12-17 18:44 UTC, marinajcs commented on Dockerfile
> +LABEL maintainer="marinacarranza@correo.ugr.es"
Gracias por la sugerencia :smile:
Añadido en: https://github.com/marinajcs/asignacionTareas/pull/33/commits/da87101c49a7365c82fdf060ef484e4de74f3a39

2023-12-17 18:45 UTC, marinajcs commented
@JJ Listo para revisión

2023-12-17 19:09 UTC, JJ requested changes
Por favor, consulta también los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-5.md), sobre todo el segundo y el tercerlo.

2023-12-17 19:09 UTC, JJ commented on Dockerfile
> +COPY --chown=node:node lib lib
No puedes copiar los contenidos del repositorio; se supone que esos contenidos tienen que estar presente sólo cuando se monte el repositio.

2023-12-17 19:29 UTC, marinajcs commented on Dockerfile
> +COPY --chown=node:node lib lib
Resuelto en: https://github.com/marinajcs/asignacionTareas/pull/33/commits/b6723ac855ffa2d2f30fc51c662ef7876bed2126

2023-12-20 07:04 UTC, JJ commented
¿Está listo para revisión?

2023-12-20 19:53 UTC, marinajcs commented
> ¿Está listo para revisión?

Tratando de resolver el problema https://github.com/marinajcs/asignacionTareas/pull/33#discussion_r1429245078, ha surgido una nueva issue (https://github.com/marinajcs/asignacionTareas/issues/35) que estuve tratando de solucionar, pero no he llegado a ninguna conclusión aún, así que había pensando en consultárselo en la clase de mañana (o el viernes).

2023-12-22 08:56 UTC, JJ approved these changes
👍

2023-12-22 09:03 UTC, merged

2023-12-22 10:25 UTC, JJ commented
Y muchas gracias a @migueruiz por la revisión.