[IV-23-24] Objetivo 6: Integración continua (CI)
marinajcs/asignacionTareas pull request #38
Opened 2024-01-09 18:58 UTC by marinajcs

* [ ] ¿Se han establecido criterios *a priori* para elegir el sistema de
integración continua más conveniente y se han calificado los sistemas que
cumplan esos requisitos según esos criterios?
* [ ] ¿Se han examinado varios sistemas de integración continua?
* [ ] ¿Se han configurado varios sistemas de integración continua?
* [ ] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [ ] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   dellenguaje con las que funciona correctamente nuestra aplicación?
* [ ] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?
* [ ] ¿Se han justificado correctamente las versiones del lenguaje que se están
testeando y se ha comprobado que no se comprueban varias veces lo mismo (la
misma versión en CI y en el contenedor Docker en otro sistema CI?

2024-01-10 20:44 UTC, carlotiii30 approved these changes
Veo que has hecho un gran trabajo de investigación. Lo veo perfecto.

2024-01-10 20:45 UTC, MarioGuisado approved these changes
En general muy completo, aunque quizás en los criterios convendría definir uno que indique que aquellas herramientas que sean usadas por muchos otros alumnos se descartarán, porque es lo que se ha usado para eliminar muchas de las opciones consideradas.

2024-01-10 21:32 UTC, marinajcs commented
@JJ Listo para revisión

2024-01-10 21:34 UTC, Enaraque approved these changes
En general lo veo bastante completo y compruebas varias versiones. Te he dejado un comentario respecto a una de las herramientas consideradas, pero buen trabajo! 💪

2024-01-10 21:34 UTC, Enaraque commented on docs/eleccion-ci.md
> +para construir, probar y desplegar software. Se terminó descartando
Jenkins es una herramienta que se tiene que instalar localmente. No la consideraría como una herramienta que podríamos usar a no ser que desees hacer una instalación local en tu PC

2024-01-15 09:20 UTC, JJ requested changes
Está bastante bien con respecto a versiones y demás, pero en los criterios de elección debéis procurar afinar y poner sólo los que realmente sean posibles elecciones.
Siento no haberlo corregido antes; durante hoy y mañana si puedes cambiarlo lo corrijo sobre la marcha.

2024-01-15 09:20 UTC, JJ commented on docs/eleccion-ci.md
> +* [**Atlassian Bamboo**](https://www.atlassian.com/es/software/bamboo): solución de CI/CD de Atlassian. Requiere
Si vas a descartarlas "automáticamente", incluirlas no genera ninguna información. Simplemente establece criterios de búsqueda e incluye solo las que cumplan esos criterios de búsqueda.

2024-01-15 09:20 UTC, JJ commented on docs/eleccion-ci.md
> +* [**Bitbucket**](https://bitbucket.org/product/es/features/pipelines): servicio de desarrollo de software que incluye
Si no se puede usar desde GitHub, igual que arriba (y con Jenkins). Has puesto como criterio "compatibilidad con herramientas actuales", igual debería ser un requisito, y no criterio.

2024-01-16 12:32 UTC, marinajcs commented on docs/eleccion-ci.md
> +* [**Atlassian Bamboo**](https://www.atlassian.com/es/software/bamboo): solución de CI/CD de Atlassian. Requiere
Resuelto en https://github.com/marinajcs/asignacionTareas/pull/38/commits/b9dead0351aacc1acd2a643d2bc8cfe8eb414009

2024-01-16 12:32 UTC, marinajcs commented on docs/eleccion-ci.md
> +* [**Bitbucket**](https://bitbucket.org/product/es/features/pipelines): servicio de desarrollo de software que incluye
Resuelto en https://github.com/marinajcs/asignacionTareas/pull/38/commits/b9dead0351aacc1acd2a643d2bc8cfe8eb414009

2024-01-16 13:59 UTC, JJ approved these changes
:+1:

2024-01-16 15:54 UTC, merged