[IV-23-24] Objetivo 2
marinajcs/asignacionTareas pull request #7
Opened 2023-10-09 08:22 UTC by shvtwp

2023-10-26 16:30 UTC, shvtwp commented
Sobre la estructura del repositorio

* [x] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [x] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?

Sobre el planteamiento

* [x] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [x] ¿Los issues representan un problema, y no una tarea?

Sobre el análisis del problema

* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [x] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

Sobre el código

* [x] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [x] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [x] ¿Todos los issues creados están relacionados con a una HU?
* [x] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [x] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [x] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [x] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2023-10-26 16:46 UTC, shvtwp commented
@marinajcs Hola Marina, ¿podrías añadir el PR al M0 y añadir la etiqueta "hacktoberfest-accepted"? Está listo para que lo revises  👍

2023-10-26 17:52 UTC, MarioGuisado requested changes
TypeScript necesita de un fichero package.json que deberás generar con objeto de mantener un historial de los paquetes instalados y optimizar la forma en que se generan las dependencias del proyecto.
En cuanto a las interfaces, siguiendo las buenas prácticas deberían describirse todas juntas en un único fichero, que será el que se importe cada vez que se necesite una. De esta manera se agrupan todas y no se deben ir buscando en los demás ficheros del proyecto cuando se necesiten.

2023-10-26 18:46 UTC, MarioGuisado approved these changes
Como apunte que no se olvide asignar todos los issues a un milestone (en este caso el 0), creo que queda por asignar el correspondiente a la elección de lenguaje.

2023-11-01 20:38 UTC, marinajcs commented
* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [ ] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2023-11-02 08:23 UTC, shvtwp commented
@JJ listo para revisión.

2023-11-08 06:50 UTC, JJ commented
Se me había pasado totalmente, perdona.

2023-11-08 06:51 UTC, JJ commented
Tendría que aprobarlo explícitamente @marinajcs antes, por eso no lo he revisado. Por favor, hacedlo lo antes posible.

2023-11-08 11:15 UTC, marinajcs approved these changes
Me parece una buena modelización del problema

2023-11-08 17:28 UTC, JJ commented
Voy a revisarlo, pero en el futuro, por favor, pedídmelo explícitamente.

2023-11-08 17:31 UTC, JJ requested changes
Me temo que no hay ni un commit que siga las mejores prácticas. No tienen la longitud correcta (50 caracteres en la primera) y mencionan el issue con el que trabajan al final, con lo que es complicado saber si se están siguiendo las buenas prácticas o no. Dejadme que le dé otro repaso para poder  ver si realmente corresponde a las HUs.

2023-11-08 17:45 UTC, JJ requested changes
OK, ya he visto en algunos casos cómo se ha desarrollado, pero en otros es imposible saberlo. En todo caso, tanto @marinajcs lo que tienen que hacer es una especie de recorrido como 
1. Tenemos unos compañeros de piso con unos horarios 
2. Hay unas tareas que tienen ¿horario?¿prioridad? 
3. Las tareas una vez realizadas ¿se almacenan en algún sitio? ¿se borran?

Convendría quizás replantearse los "issues-son-objetos-o-entidades" y convertirlos en "issues-son-problemas". Como no está claro qué código se ha desarrollado con respecto a qué issue, en algunos casos se puede reescribir; en otros habrá que marcarlo como inválido y cerrarlo cuando se fusione el PR.

2023-11-08 17:45 UTC, JJ commented on lib/compi.ts
> +        readonly id: number,
Los objetos valor nunca tienen un ID. Pueden usar un string para identificarlos, pero no necesariamente dentro de un objeto. Como he dicho en #8, empezar por una estructura determinada te fuerza a crearla; si te fijas en qué problema hay o cómo se van a usar en la lógica de negocio saldrán de forma natural las estructuras necesarias.
En todo caso, el issue #8 tampoco dice nada de un ID.

2023-11-08 17:45 UTC, JJ commented on lib/horario.ts
> +        private readonly idpiso: number,
Bien por el uso de la forma condensada de los constructores de TS, pero una vez más, ¿qué uso va a darle la lógica de negocio al id?

2023-11-08 17:45 UTC, JJ commented on lib/zonascomunes.ts
> +export class ZonasComunes {
A través de los cambios de nombre de fichero he perdido cuál es el issue que se está desarrollando aquí. Es importante que siempre, incluso en los cambios, se ponga el issue porque es documentación para la persona que revisa y saber si está bien o mal.

2023-11-08 17:45 UTC, JJ commented on lib/zonascomunes.ts
> +    realizada: boolean;
Los objetos valor deben ser inmutables.  Hay otra forma de gestionar si una tarea se ha realizado o no, usando entidades. Convendría que consideraras cómo hacerlo de esa forma.

2023-11-10 18:05 UTC, shvtwp commented
@marinajcs He hecho nuevas modificaciones significativas, así que creo que deberías volver a revisar los cambios antes de solicitar revisión

2023-11-11 17:50 UTC, marinajcs requested changes
Exceptuando dos pequeños detalles, me parece un modelo del problema correcto y una buena base para las futuras etapas de desarrollo.

2023-11-11 17:50 UTC, marinajcs commented on lib/reparto.ts
> +type Tarea = {
Por lo que tengo entendido, puntuación es el nivel de dificultad de la tarea, lo que me parece buena idea de cara a realizar una asignación más equitativa.

Como sugerencia, se podría añadir a las tareas una propiedad opcional: `personasNoPermitidas?: Compi[];`  
Así, también podría abordarse la HU02 #4

2023-11-11 17:50 UTC, marinajcs commented on lib/reparto.ts
> +type Tarea = {
Adicionalmente, el nombre de la tarea no es necesario para implementar la lógica de negocio

2023-11-11 18:00 UTC, marinajcs commented on iv.yaml
> +entidad: lib/Horario.ts
También faltaría actualizar la entidad a `lib/reparto.ts`

2023-11-13 09:04 UTC, shvtwp commented
@marinajcs He actualizado según los cambios que me has dicho. En lugar de añadir una representación de las preferencias en Tarea, la he añadido en los propios Compis con el fin de representar de manera más intuitiva las preferencias personales. Revísalo y comunícame si tienes alguna otra sugerencia.

2023-11-13 19:53 UTC, marinajcs approved these changes
Me parece bien

2023-11-13 19:54 UTC, marinajcs commented
Listo para revisión @JJ

2023-11-14 12:01 UTC, JJ approved these changes
:+1: 
Quizás no deberías haber incluido ningún setter, pero si @marinajcs lo ha aprobado, me vale.

2023-11-14 15:45 UTC, merged